### ISSUE TITLE
ModuleNotFoundError: No module named 'FundamentalAnalysis' 

### ISSUE THREAD

**Issue by rosensuzie** [DidierRLopes/GamestonkTerminal#14]
`import FundamentalAnalysis as fa ModuleNotFoundError: No module named 'FundamentalAnalysis' `
I'm getting this error while running, even after installing all the dependencies

**Comment by DidierRLopes** [comment]
Can you re-attempt to run pip install FundamentalAnalysis ?

Do you have a valid Financial Modeling Prep key?

You can see more in here:
https://github.com/JerBouma/FundamentalAnalysis

**Comment by mubbud** [comment]
I have the same error in fundamental_analysis as well as in discovery even though I have successfully installed Fundamental Analysis and I have obtained all the API Keys mentioned (Alpha Vantage, Financial Modeling Prep, Quandl, Reddit, Twitter)

ModuleNotFoundError: No module named 'fundamental_analysis'

**Comment by DidierRLopes** [comment]
The fundamental_analysis module comes from the Financial Modeling Prep.

So I guess you are having troubles with all commands related with this module, correct? Mainly in Fa menu? Are you using?
```
FundamentalAnalysis==0.2.6
```

**Comment by mubbud** [comment]
That's right, I have troubles in Fa menu, however Financial Modeling Prep runs absolutely fine.
Thanks for your swift reply.

**Comment by BigCandyBunny** [comment]
The reason for this error is because the import statement calls for FundamentalAnalysis while the folder with the scripts is named fundamental_analysis. Thus, either change the named on the folder to FundamentalAnalysis or correct the spelling in the the 2-3 scripts with this error to fundamental_analysis.

Imports point to a folder where GamestonkTerminal is running, this is not a library issue.

**Comment by mubbud** [comment]
Zillion thanks for getting me in the right direction, Problem Solved.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
