### ISSUE TITLE
Unable to get output of lstm feature

### ISSUE THREAD

**Issue by Quickpipsfx** [DidierRLopes/GamestonkTerminal#154]
![image](https://user-images.githubusercontent.com/80470045/110804319-139a6680-82a6-11eb-8e26-d2d09462bc4f.png)

This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by DidierRLopes** [comment]
Hey @Quickpipsfx ,

I don't actually have GPU on my machine, so I can't replicate this.

Can you have a look at this thread https://github.com/tensorflow/tensorflow/issues/45853
and let me know.

Does this happen only for lstm? Or also for mlp and rnn?

Thanks in advance!

**Comment by Quickpipsfx** [comment]
yeah same is happening with mlp and rnn but I managed to make it work by changing the name of one the dll CUDA file so it doesn't load and start processing with Processor i guess.

![image](https://user-images.githubusercontent.com/80470045/110910082-e5189c00-8336-11eb-9fdd-5012fe9dd152.png)


so now am able to see the chart and prediction output 

![image](https://user-images.githubusercontent.com/80470045/110910144-f497e500-8336-11eb-9bc5-9e5138c63388.png)

**Comment by DidierRLopes** [comment]
Great that you made it work! 

I've added a nice text in here: https://github.com/DidierRLopes/GamestonkTerminal/issues/58#issuecomment-787210229

I think that due to its nature LSTM will always be better than MLP and RNN. Because:
- MLP: The neurons don't have any memory
- RNN: The neurons can only retain really recent memory
- LSTM (improved RNN): The neurons have a good memory, hence why this is used for text prediction, since the beginning of a sentence is important to predict the ending.

A good outlook regarding LSTM: https://colah.github.io/posts/2015-08-Understanding-LSTMs/

Let me know if this helped.I'll close this ticket for now
