### ISSUE TITLE
[FR] Add the Stock Analysis website

### ISSUE THREAD

**Issue by kristjanmar** [DidierRLopes/GamestonkTerminal#172]
Thanks for making the GameStonk terminal! I’m the owner of stockanalysis.com, any chance you could check it out and add it to the “Research Web Pages” if you think it is useful?

Also, my site has pretty detailed financial data with up to 25 years of financial history. It is easy to parse with python as long as it doesn’t do too many requests at once. It works great if just fetching one or several stocks at a time.

**Comment by DidierRLopes** [comment]
Your website has now been added to research menu! Thank you for this, it is a great addition to our terminal!

Will close this PR on that basis.

**Comment by DidierRLopes** [comment]
Hey @kristjanmar,

Have a peek at #454, @jmaslek added an ETF menu based on data from your page.  :)

**Comment by kristjanmar** [comment]
Oh sweet, thanks for letting me know :)

**Comment by jmaslek** [comment]
Hey @kristjanmar, thanks for the data!  I was thinking about coding up an etf screener using your overview data.  However it takes > 10 minutes to loop through and request each individually (hope thats not an issue for your server either).  I was curious if you had any ideas for parsing quicker, or if you had a database we could directly query.  Thanks!

**Comment by kristjanmar** [comment]
Hey @jmaslek I don't think I'm allowed to share the data in that way, I pay for this data from Barchart and Finnhub using their website display licenses.

**Comment by jmaslek** [comment]
@kristjanmar We noticed you guys changed up your website (due to some flawed design with the terminal, it crashed the terminal because the scraping failed).  I am trying to rewrite the scraping of your ETF stuff and for getting all the symbols, I only get the first 500.  Playing around I noticed all your ETFS come from an etf.json: (URL: https://stockanalysis.com/_next/data/7MjLxqXW9_Sr_UQ9mqQxJ/etf.json )

However that string between data/ and /etf changed from last night to this morning.  Not sure if I shouldn't be pulling that directly or if there is something I can do to make my life easier (I assume same with the holdings.json).

**Comment by kristjanmar** [comment]
Sorry about that, I just moved my site over to React/NextJS but still using the old site's WordPress backend for the data.

The old site is now running at api.stockanalysis.com. It is noindexed but can be accessed and is still updating with fresh data.

So if you change the URLs to the api. subdomain then the original functions should work just as before.

**Comment by jmaslek** [comment]
Awesome!  Thanks for the quick reply and the information!
