### ISSUE TITLE
NOT RESPONDING

### ISSUE THREAD

**Issue by Quickpipsfx** [DidierRLopes/GamestonkTerminal#174]
I didn't have this issue in the old version of stonk, I tried to build a fresh environment as well and still the figures are not responding, Help me if anyone faced the same issue.

p.s. the figures in discover function are showing but in TA and PRED it's not

![image](https://user-images.githubusercontent.com/80470045/111112545-59954a00-8586-11eb-9483-6b06a7b99aad.png)

**Comment by aia** [comment]
see https://github.com/DidierRLopes/GamestonkTerminal/pull/158

**Comment by Quickpipsfx** [comment]
@aia  am still unable to resolve it :/

**Comment by DidierRLopes** [comment]
Hey @Quickpipsfx the issue is that you must have both USE_ION and USE_PROMPT_TOOLKIT set to true. This is not yet compatible, unfortunately.

Set one of them to true, and other to false, in here:
https://github.com/DidierRLopes/GamestonkTerminal/blob/8508b166f41d93e39ce00a3b91140d7fdc5dbcd9/gamestonk_terminal/feature_flags.py#L5

and it should work! Let me know if it doesn't!

**Comment by Quickpipsfx** [comment]
> Hey @Quickpipsfx the issue is that you must have both USE_ION and USE_PROMPT_TOOLKIT set to true. This is not yet compatible, unfortunately.
> 
> Set one of them to true, and other to false, in here:
> https://github.com/DidierRLopes/GamestonkTerminal/blob/8508b166f41d93e39ce00a3b91140d7fdc5dbcd9/gamestonk_terminal/feature_flags.py#L5
> 
> and it should work! Let me know if it doesn't!

Yes I got it now, It's Fixed Thanks !!
