### ISSUE TITLE
[IMPROVE] Automatically adjust the figure window size according to screen size 

### ISSUE THREAD

**Issue by avocardio** [DidierRLopes/GamestonkTerminal#180]
**What's the feature that should be improved?**
I have to adjust the view or pred figures every time I run them, and they sometimes don't scale well. 

**Describe how you would like the feature improved**
I would like the figures to open a little bit bigger or at least according to some screen ratio. 

I have no idea how to do this, but I was going to try this myself but I have no idea where I would find this under the files? @DidierRLopes is there one single file that draws the figures or would I need to dig into every single file? Thanks for the help.

**Comment by DidierRLopes** [comment]
Hey @avocardio ,

This contribution would be extremely welcome.

The lines you are looking for are:
`plt.figure()`

For instance in Arima case, that is:
https://github.com/DidierRLopes/GamestonkTerminal/blob/ce31ff6245489b535385105a3a3560e9b9fb7bac/gamestonk_terminal/prediction_techniques/arima.py#L171
and
https://github.com/DidierRLopes/GamestonkTerminal/blob/ce31ff6245489b535385105a3a3560e9b9fb7bac/gamestonk_terminal/prediction_techniques/arima.py#L244

There's always 2 plt.figures() per file, that's due to backtesting.

If you found a way that this scaling would work well for all OS, you could literally due a plt.figure() Replace all.

**Comment by buzzCraft** [comment]
I see that https://pypi.org/project/screeninfo/ will provide screen resolution for Win/Mac/Unix. If you are open to have yet another package imported, I'll start looking into it.

**Comment by DidierRLopes** [comment]
As long as it improves the user experience, I'm happy with more packages being imported! Thank you for this :)

PS: #189 will be merged soon. This touches the Neural Network figures code, so watch-out for conflicts when you create the PR.

**Comment by buzzCraft** [comment]
I'm thinking about making config_plot.py where you can set the size of plots. After looking into autoscaling, I don't think this is the way to go. I'll keep it as an option and let you decide later.

**Comment by DidierRLopes** [comment]
Sounds good to me!

If you think autoscaling may not be suitable for everyone,  but for some users it will. You can add it behind a feature flag, look into feature_flags.py.

E.g.
`
if gtff.USE_PLOT_AUTOSCALING:
   plt.figure(autoscaling nice feature)
else:
   plt.figure( get resolution from config_plot file)
`

**Comment by DidierRLopes** [comment]
@buzzCraft has worked on this and his improvements are already merged.

Will keep this PR open since @buzzCraft will expand this improvement to the prediction figures.

**Comment by DidierRLopes** [comment]
Closing this because of @buzzCraft contribution. Thanks!
