### ISSUE TITLE
module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by pelcasandra** [DidierRLopes/GamestonkTerminal#19]
Using python 3.8:

```
python3 gamestonk_terminal.py 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "gamestonk_terminal.py", line 6, in <module>
    from helper_funcs import *
  File "/Users/pel/Projects/Gamestonk/GamestonkTerminal/helper_funcs.py", line 9, in <module>
    import matplotlib
  File "/Users/pel/Library/Python/3.8/lib/python/site-packages/matplotlib/__init__.py", line 205, in <module>
    _check_versions()
  File "/Users/pel/Library/Python/3.8/lib/python/site-packages/matplotlib/__init__.py", line 190, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
```

```
pip3 show numpy
Name: numpy
Version: 1.19.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /Users/pel/Library/Python/3.8/lib/python/site-packages
Requires: 
Required-by: yfinance, transformers, torch, TimeSeriesCrossValidation, tensorflow, tensorboard, statsmodels, scipy, scikit-learn, Quandl, pystan, pmdarima, patsy, pandas, opt-einsum, matplotlib, Keras-Preprocessing, hyperopt, h5py, gensim, fbprophet, cmdstanpy, bpemb
```

**Comment by jakobakoba** [comment]
i have ubuntu, this command in anaconda environment fixes the problem: pip install -U numpy

**Comment by DidierRLopes** [comment]
Hey,

I've tested with Python 3.6.8, which hasn't show me this.

Anyway, I'm refactoring the whole requirements.txt file, and installation process will be much smoother once I push the changes!

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔

**Comment by phgmacedo** [comment]
While trying to install via the "requirements.txt" using pip, i'm getting the same error.
