### ISSUE TITLE
Setup Instructions for MacOS 11.2.1

### ISSUE THREAD

**Issue by Grabes** [DidierRLopes/GamestonkTerminal#21]
Thanks for creating this package, it looks quite nice. 

I ran into a couple errors while installing the pip requirements and I am documenting them here.

1. Installed Python 3.6.8 as per the build instructions but received an error saying python > 3.7 was required
```
'gensim.models.fasttext_inner': 'gensim/models/fasttext_inner.c',
    RuntimeError: Python version >= 3.7 required.
```
I ran `pyenv install 3.7.10` and `pyenv global 3.7.10` to resolve this error.

2. The second was by missing the wheel package. Running `pip install wheel` resolved the issue.
3. Received the following error.
```
numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
```
Attempting to install blas using `brew install llvm@9 openblas`

**Comment by DidierRLopes** [comment]
Hey,

Thanks for feedback.

I'm improving the pip requirements this weekend, as it seems to be a major bottleneck as is.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
