### ISSUE TITLE
[Bug]poetry install - FileNotFoundError

### ISSUE THREAD

**Issue by hlchan-sg** [DidierRLopes/GamestonkTerminal#211]
Hi I have activated conda GST and is at the step - poetry install

there is this error message:

FileNoteFoundError

[WinErrror 2] The system cannot find the file specified

~\anaconda3\envs\gst\lib\subprocess.py:1017

any help on this?

many thanks/

**Comment by aia** [comment]
Try following the same steps as we have in Github CI - 

https://github.com/DidierRLopes/GamestonkTerminal/actions/workflows/windows.yml

**Comment by jmaslek** [comment]
Did you conda install poetry?

**Comment by hlchan-sg** [comment]
yes install poetry has no issues encountered

**Comment by hlchan-sg** [comment]
i fork the github to "documents" of the user folder
cd into GamestonkTerminal folder
conda install poetry
proceed? yes
executing: done.

next i key poetry install

it shows FileNotFoundError
[WinError 2] The system cannot find the file specified
~\anaconda3\envs\gst\lib\subprocess.py:1017

**Comment by aia** [comment]
I'd suggest repeating what Windows CI is doing step-by-step.

<img width="1146" alt="windows-ci" src="https://user-images.githubusercontent.com/535247/111523315-5f229980-8718-11eb-969c-96cbe0cb8b35.png">

**Comment by cknig** [comment]
Yes I also suggest  Windows CI

**Comment by saintsupremacy** [comment]
I think i found a solution for now only because I played around with it. I had the same issue as you. follow the guide up to the point where it says "conda install poetry" once thats done youre going to want to "pip install -r requirements" once that is processed you might get something saying you need 'git' so then you type "conda install -c conda-forge git"  once thats all done you can now type "poetry install"

**Comment by hlchan-sg** [comment]
Hi Saint et al.

Sorry been away for a while. 

Saint solution worked like a charm and it is the solution given by aia and cknig.
