### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement scipy==1.6.1 on Mac OS 

### ISSUE THREAD

**Issue by alifa133** [DidierRLopes/GamestonkTerminal#25]
using virtual env with python version 3.6.8
Mac OS 11.2.1

when trying to install requirements get the this:

ERROR: Could not find a version that satisfies the requirement scipy==1.6.1

anyone else got the same error?

Thanks!

**Comment by chris-jones** [comment]
I think it's related to a minor outage on Pypi (https://status.python.org/) try again later on and you should shave some success.

**Comment by chris-jones** [comment]
Scipy pequires: Python >=3.7

You'll need to update your python version to use it.

(see: https://pypi.org/project/scipy/1.6.1/)

**Comment by adamlaz** [comment]
I had/have the same issue... 

```bash
pyenv local 3.6.8 # Because this was mentioned in readme install section
pip install -r requirements.txt
...
ERROR: Could not find a version that satisfies the requirement scipy==1.6.1
ERROR: No matching distribution found for scipy==1.6.1
```

**I have it (mostly) working with Python `v3.7.7`**
```bash
pyenv local 3.7.7
pip install -r requirements.txt
...
python gamestonk_terminal.py
Welcome to Didier's Gamestonk Terminal
...
```

I tried v3.7.7 for no other reason than I had that version already installed via pyenv. Also, it doesn't install properly with 3.8.1. There are some errors that I've seen so far _(eg. Importing plotly failed. Interactive plots will not work.)_ ... So I'm not going to open a PR to update readme until I play with this some more and ...either know "everything" is working... or, do fixes needed. 

Just posting this here so others that get the error can try using this version/etc.

**Comment by Ulmerjm** [comment]
I have found that if you edit the requirments.txt and have

> scipy

Instead of

> scipy==1.6.1

Pip will automatically find and install version 1.6.1 on its own. Your milage may vary here but it is worth a shot.

**Comment by DidierRLopes** [comment]
Hey @alifa133,

Thank you for pointing this out. The scipy version should have been the 1.4.1 in the first place. I'll fix this soon, along with all requirements.txt fixes.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
