### ISSUE TITLE
Window 10

### ISSUE THREAD

**Issue by filharvey** [DidierRLopes/GamestonkTerminal#30]
A continuation of the issuses on windows

Sorry one more, just was able to do that last one

Traceback (most recent call last):
File "gamestonk_terminal.py", line 12, in
from prediction_techniques import pred_menu as pm
File "C:\GamestonkTerminal\prediction_techniques\pred_menu.py", line 16, in
from prediction_techniques import fbprophet
File "C:\GamestonkTerminal\prediction_techniques\fbprophet.py", line 11, in
from fbprophet import Prophet
ModuleNotFoundError: No module named 'fbprophet'

**Comment by sigaloid** [comment]
Run `pip install fbprophet` (or re-clone the repository and re-run `pip install -r requirements.txt` as this was just fixed recently)

**Comment by filharvey** [comment]
Thanks did that, one more

Could not find a version that satisfies the requirement scipy==1.6.1 (from -r requirements.txt (line 90)) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
No matching distribution found for scipy==1.6.1 (from -r requirements.txt (line 90))

**Comment by sigaloid** [comment]
I'm not on windows but try `pip install scipy`, it's possible that specific version isn't necessary.

**Comment by saintsupremacy** [comment]
> Thanks did that, one more
> 
> Could not find a version that satisfies the requirement scipy==1.6.1 (from -r requirements.txt (line 90)) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
> No matching distribution found for scipy==1.6.1 (from -r requirements.txt (line 90))

Try going into the requirement.txt file and changing scipy 1.6.1 >>>1.5.2

**Comment by DidierRLopes** [comment]
Hey guys,

fbprophet dependencies have been a nightmare. I'm attempting to have it working smoothly soon.

Regarding scipy, you're right. It should have been 1.4.1. @filharvey 

Hope this helps!

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
