### ISSUE TITLE
Cannot Install FBProphet

### ISSUE THREAD

**Issue by Ulmerjm** [DidierRLopes/GamestonkTerminal#35]
I am working through the dependencies on windows and have finally run into a snag I haven't been able to figure. During the fbprophet installation, the environment notices that pystan is missing and installs Cython, pystan, fbprophet, config, beautifulsoup4, alpha-vantage. After this, it retries running setup.py for fbprophet and quickly fails due to not finding pystan despite it being installed in the enviroment. Any guesses here?

Running 64 bit Windows 10 and an Intel i9. Sorry in advance for the poor formatting below I couldn't hunt down where it spit out the log file.

> Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: Cython, pystan, fbprophet, config, beautifulsoup4, alpha-vantage
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jack\\AppData\\Local\\Temp\\pip-install-ilbs4rh4\\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jack\\AppData\\Local\\Temp\\pip-install-ilbs4rh4\\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Jack\AppData\Local\Temp\pip-record-z8zczdsi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\include\site\python3.6\fbprophet'
         cwd: C:\Users\Jack\AppData\Local\Temp\pip-install-ilbs4rh4\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Importing plotly failed. Interactive plots will not work.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Jack\AppData\Local\Temp\pip-install-ilbs4rh4\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\setup.py", line 149, in <module>
        long_description_content_type='text/markdown',
      File "c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
      File "c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\command\build.py", line 135, in run
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Jack\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
      File "C:\Users\Jack\AppData\Local\Temp\pip-install-ilbs4rh4\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\setup.py", line 48, in run
        build_models(target_dir)
      File "C:\Users\Jack\AppData\Local\Temp\pip-install-ilbs4rh4\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "C:\Users\Jack\AppData\Local\Temp\pip-install-ilbs4rh4\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\fbprophet\models.py", line 209, in build_model
        import pystan
      File "c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\lib\site-packages\pystan\__init__.py", line 9, in <module>
        from pystan.api import stanc, stan
      File "c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\lib\site-packages\pystan\api.py", line 13, in <module>
        import pystan._api  # stanc wrapper
    ImportError: DLL load failed: The specified module could not be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jack\\AppData\\Local\\Temp\\pip-install-ilbs4rh4\\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jack\\AppData\\Local\\Temp\\pip-install-ilbs4rh4\\fbprophet_381b22e31e0d4e2d9547bbde2aeb1418\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Jack\AppData\Local\Temp\pip-record-z8zczdsi\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\jack\desktop\projects\python\gamestonkterminal-main\env\include\site\python3.6\fbprophet' Check the logs for full command output.

**Comment by Snorchy** [comment]
I also had trouble with dependencies. I haven't been able to install it on WSL2 ("Virtualised" Linux) in Windows after trying for like... 5 hours. I tried Python 3.6, 3.8 and 3.9 and I always hit some dependency that couldn't be installed. Even when I installed them manually (and succeeded that way) then I would hit another error anyways. The one that was unsurmountable to me was the "Carbon/Carbon.h" missing dependency which I think is only for Mac OS. I even seemed random sometimes, in my case it wasn't consistent which dependency would error out.

**Comment by Ulmerjm** [comment]
If I read correctly on a different issue page the error with Carbon is a result of appscript which is actually unused in the code. Try removing that from the requirments.txt and you should be golden.

I'm just confused because the code was written and tested on Python 3.6.8 but pystans current requirements per their docs is python 3.7 or higher... maybe this is the root of the issue?

**Comment by Snorchy** [comment]
That shocked me a bit as well, yes. Weird.

**Comment by tigwyk** [comment]
I'm currently experiencing the exact same issue with fbprophet, Win10 x64 on an i7.

No matter how I try to shovel pystan at fbprophet, it won't build the wheel.

**Comment by Snorchy** [comment]
I DID IT! Well, until execution, but at least I solved the problem of installing with Python 3.8.5 in WSL2 in Windows. For me the solution was to manually install all the packages that gave me error during the build, which were: xlwings, scipy, matplotlib and fbprophet. So the commands I ran were: `export INSTALL_ON_LINUX=1 && pip install --no-cache-dir wheel xlwings scipy matplotlib fbprophet && pip install --upgrade -r requirements.txt`

That way the conflicting programs were installed before the requeriments.txt dependencies and thanks to the --upgrade parameter they weren't reinstalled if they were encountered inside requeriments.txt. Also I had to do the indicated changes [in here](https://github.com/DidierRLopes/GamestonkTerminal/pull/13#issuecomment-785809870) to requeriments.txt.

Now my problem is that anyt graphics appears on the screen but that's probably due to me running into WSL which has no GUI output support (It seems I'm a WSB smooth brained retard after all yay!).

Will try on Windows another time.

**Comment by Ulmerjm** [comment]
From all, I have been reading there is a limitation with pystan and windows which can be resolved by adding a separate compiler to the PATH, alternatively, you can get these troublesome libraries working with docker so I might give that a try tonight personally.

**Comment by tigwyk** [comment]
Since I'm trying to keep this install native to Windows (without resorting to WSL), I've tried a method installing mingw32 and using that compiler instead, but no matter what I still get the same errors when trying to compile the wheel so I suspect I'm missing a step somewhere. I'll report back if I make any headway.

**Comment by Ulmerjm** [comment]
I also saw the suggestion of mingw32, but didn't try it myself. I have heard that you can get fbProphet installed on conda using a special conda-forge wheel but that was very slow and didn't seem to work properly.

For the time being, I have commented out the fbProphet class (which is the only place pystan is used to my knowledge) and have been running the code just fine. That might be the best solution for native Windows users albeit at the cost of one of the sources.  One particularly frustrating thing I noticed in my hunt to get these two packages working was there seems to be at some point an official(?) docs page for getting them to work on windows. The page is no longer available and the developers are award that the package doesn't work on Windows so it might not ever be supported.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
