### ISSUE TITLE
Can't run app / can't install appscript and fbprophet

### ISSUE THREAD

**Issue by bjeale** [DidierRLopes/GamestonkTerminal#37]
This is what I get when trying to run it. Couldn't install appscript and fbprophet. Python 3.8.8 (Win 10)

(venv_for_GamestonkTerminal) D:\Downloads\GamestonkTerminal-main>gamestonk_terminal.py
Traceback (most recent call last):
  File "D:\Downloads\GamestonkTerminal-main\gamestonk_terminal.py", line 12, in <module>
    from prediction_techniques import pred_menu as pm
  File "D:\Downloads\GamestonkTerminal-main\prediction_techniques\pred_menu.py", line 16, in <module>
    from prediction_techniques import fbprophet
  File "D:\Downloads\GamestonkTerminal-main\prediction_techniques\fbprophet.py", line 11, in <module>
    from fbprophet import Prophet
ModuleNotFoundError: No module named 'fbprophet'

(venv_for_GamestonkTerminal) D:\Downloads\GamestonkTerminal-main>

**Comment by avocardio** [comment]
I just left fbprophet out of the script by just commenting out the code in the file and it ran fine without it. You just wont be able to use facebook trend data, which is not really important anyway.

**Comment by bjeale** [comment]
What exactly did you comment out?

**Comment by juaudet** [comment]
Comment out the class : fbprophet in \GamestonkTerminal\prediction_techniques\fbprophet.py

**Comment by jamesphillipturpin** [comment]
On Windows you need to use the wheel from conda-forge according to here:
[https://github.com/facebook/prophet/issues/89](https://github.com/facebook/prophet/issues/89)

I'm trying to do that just now, haven't got it working yet myself yet.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
