### ISSUE TITLE
Segmentation fault: 11 (OSX) when trying to run 'view' or 'pred' 

### ISSUE THREAD

**Issue by avocardio** [DidierRLopes/GamestonkTerminal#4]
Pretty new to this; when trying to run view or pred, like using knn, a little file pops up but then closes after a few seconds and gives me this error. 

![Screen Shot 2021-02-24 at 9 49 28 PM](https://user-images.githubusercontent.com/74978236/109100492-ab1a8980-76ea-11eb-9b40-4ab3d5ba64e5.png)

**Comment by noahkuhn** [comment]
Seeing this as well, macOS 11.2.1, using Python 3.8.7 via a pyenv virtualenv.

**Comment by DidierRLopes** [comment]
This is odd I didn't have such issue.

Can you try to load a dataframe partially? I.e. set a starting date?

You can do so with:
`load -t GME -s 2020-06-04`

And then attempt view, or pred funcs.

It may be due to the size of the dataframe we're getting from Alpha Vintage. But I'd find it odd that you are seeing this issue and I'm not. I'm using Python 3.8.6 on a macOS 10.13.6

**Comment by noahkuhn** [comment]
I just ran that and it just does the segfault. I think this is a macOS 11 issue. Hopefully it can be sorted out, I'd love to have a crack at this thing!

`> view
[1]    74984 segmentation fault  python gamestonk_terminal.py`

**Comment by noahkuhn** [comment]
I got this to work by scrapping pyenv virtual environments and just using virtualenv directly. Took a ton of manual pip installs to get all dependencies, but I think I'm in the clear. Not sure if the person that posted this issue was using pyenv & virtualenv.

**Comment by DidierRLopes** [comment]
Nice!

@avocardio can you try instead of using pyenv & virtualenv, to use only virtualenv directly?

Yes, the pip install dependencies have been a bit of a nightmare :/

**Comment by nitsujri** [comment]
@noahkuhn I ran into the same problem but am a python amateur. 

Specifically, how do you not use pyenv and use virtualenv directly?

I thought I was doing that by

 - `rm .python-version`
 - `pip install -r requirements.txt`

Now my prompt looks like `GamestonkTerminal git:(main)` instead of `(gamestonk) GamestonkTerminal git:(main)`, so I thought that was using it without pyenv, but honestly I'm not sure where `pip install` is going when I don't have the `(gamestonk)` prefix.

But I still get a segfault trying to run View.

**Comment by michalchmura** [comment]
Same issue here

**Comment by noahkuhn** [comment]
Fellow novice here too, so this might not be the best method, but try this. Pretty sure this is what worked for me. Granted I'm still getting some other errors doing various things:

- `pyenv deactivate`
- `pyenv virtualenv-delete gamestonk`
- `pip install virtualenv`
- `virtualenv venv`
- `source venv/bin/activate`
- `pip install -r requirements.txt`
- `python gamestonk_terminal.py`

You will likely get an error and be missing a bunch of dependencies so just note the module name at the bottom of the error and keep running 

`pip install xxxxxxx`

and then retrying

`python gamestonk_terminal.py`

until it works... My guess is that @DidierRLopes is going to tighten the hell out of this thing.

**Comment by emilepetrone** [comment]
What version of `fbprophet` are you running?

**Comment by noahkuhn** [comment]
If you're asking me: 0.7.1

**Comment by avocardio** [comment]
> Nice!
> 
> @avocardio can you try instead of using pyenv & virtualenv, to use only virtualenv directly?
> 
> Yes, the pip install dependencies have been a bit of a nightmare :/

How exactly do I use virtualenv directly? I have been trying by reinstalling like @noahkuhn did but sadly has not worked for me.

**Comment by noahkuhn** [comment]
Hmm, that should work. Basically you need to get out of whatever pyenv virtualenv you are in, then make sure you have virtualenv installed to begin with, go into your project folder, create a new virtualenv using the virtualenv command (NOT pyenv virtualenv) and then activate it. At that point you can use pyenv to set the Python version.

Again, I'm just learning python so this might all be bad practice, but it's what worked for me.

**Comment by d0tkom** [comment]
Update your matplotlib from 3.1.1 to 3.3.3 and it should work.

**Comment by DidierRLopes** [comment]
Hey guys,

Sorry for all the issues with the requirements. I didn't expect so many people to be interested in this project, hence why didn't have a more robust "installation" process.

I'm working on these during weekend:
- Using poetry to manage packages
- Reduce requirements to whatever is strictly necessary
- Making sure I can run a docker image from this

Bear with me since I'm new to these topics, but this should allow for the code to be much more smooth in installation process.

**Comment by nitsujri** [comment]
Came back to report that switching to `pyenv` + `poetry` it all works great!

Thanks so much @DidierRLopes + team. For me personally, this issue is closed.

**Comment by michalchmura** [comment]
For myself, upgrading `matplotlib 3.1.1 → 3.3.3` fixed it

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. 

The project has been testest to work with Pythons `3.6.8`, `3.7` and `3.8`. 

We are using `poetry` to manage the project and that is one option for installing. The other is to install with the `requirements.txt`. Feel free to use any virtual environment you want. 

Just make sure to run `pip install --upgrade pip` as that was affecting some people as `tensorflow` requires pip >= 2.19 (or something like that). 

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub. 

Oh and Windows is only supported with docker because `pystan` is not available for windows (officially).

If you are having problems please open a new issue =). 

🚀 GamestonkTerminal 🌔
