### ISSUE TITLE
After running don't see anything?

### ISSUE THREAD

**Issue by mxjchen** [DidierRLopes/GamestonkTerminal#40]
I tried running:
> load -t GME -s 2020-02-25 -i 5
Loading Intraday 5min GME stock with starting period 2020-02-25 for analysis.
>

But the command finished and I'm not seeing anything? Am I doing something wrong? Don't see errors either..

Thanks

**Comment by sigaloid** [comment]
The stock data is loaded into memory. That's all the command does, since many different things can be done with it once it's loaded. Run `view` or see this for more info: https://github.com/DidierRLopes/GamestonkTerminal#features-

**Comment by mxjchen** [comment]
I see, so the correct way is to run load then run view?
In that case I get segmentation fault, any ideas?

> load -t GME -s 2020-02-25 -i 5
Loading Intraday 5min GME stock with starting period 2020-02-25 for analysis.

> view -t GME -s 2020-02-25 -i 5
zsh: segmentation fault  python3 gamestonk_terminal.py

**Comment by DidierRLopes** [comment]
Hey @mxjchen ,

Exactly what @sigaloid said.

So, once you do:
```
load -t GME -s 2020-02-25 -i 5
```
you're loading GME stock starting of 25 Feb 2020 intraday 5 minutes.

When you run `view`. You don't need to redefine such arguments, since that's already what is loaded in the memory.

When you look for intraday data (`-i 5`) it means that instead of getting the usual 1 per day [open, close, high, low, volume] columns, you get 1 of these every 5 minutes.

Since market is open for 6h30m = 390m. You get 78 data rows per day (390/5). So your request of getting all 5minutes intraday GME data since last year, may be too much memory for your machine.

Try with a smaller period of time, e.g. 2021-01-01. Or without the intraday flag (-i).

Let me know if it worked.

**Comment by mxjchen** [comment]
Thanks man, so I took your suggestion and tried to just for one day and without the intraday flag, but I still get the segmentation flag, any ideas? :( or if there a way for me to provide more logs?

> load -t GME -s 2021-02-26
Loading Daily GME stock with starting period 2021-02-26 for analysis.

> view -t GME
zsh: segmentation fault  python3 gamestonk_terminal.py

**Comment by sigaloid** [comment]
Run just `view`

**Comment by mxjchen** [comment]
Yea its the same as with just view..

> load -t GME -s 2021-02-26
Loading Daily GME stock with starting period 2021-02-26 for analysis.

> view
zsh: segmentation fault  python3 gamestonk_terminal.py

**Comment by sigaloid** [comment]
Try a different shell. Are you on mac or linux? Running those commands works for me.

**Comment by mxjchen** [comment]
I'm on mac, tried bash and zsh and same result. But I am running on virtual environment in order install everything in requirements.txt, do you also keep running gamestonk_terminal.py in virtual environment after installation?

**Comment by sigaloid** [comment]
Try a different shell. Are you on mac or linux?

**Comment by sigaloid** [comment]
No, I run it in regular python.

**Comment by shadycuz** [comment]
@mxjchen 
Can you look at #4 ? I think they had the same issue and figured it out.

**Comment by mxjchen** [comment]
Yes this works! updated matlibplot to 3.3.3 no more segmentation fault
