### ISSUE TITLE
after following a guide that was posted on the thread i tried running the gamestonk_terminal within anaconda but i keep getting an error 

### ISSUE THREAD

**Issue by saintsupremacy** [DidierRLopes/GamestonkTerminal#41]
(terminal) C:\Users\Diego>C:\Users\Diego\Documents\GitHub\GamestonkTerminal\gamestonk_terminal.py
Traceback (most recent call last):
  File "C:\Users\Diego\Documents\GitHub\GamestonkTerminal\gamestonk_terminal.py", line 6, in <module>
    from helper_funcs import *
  File "C:\Users\Diego\Documents\GitHub\GamestonkTerminal\helper_funcs.py", line 3, in <module>
    from holidays import US as holidaysUS
ModuleNotFoundError: No module named 'holidays'

Link to guide https://imgur.com/a/gqgVJPn

Ive already tried conda install holidays and theyre all in there. I dont know what to do now as the python file refuses to open.

*SOLVED* it looks like while everything else was in check all i had to do was open the .py file through anaconda so essentially just this: Python 
C:\Users\Diego>C:\Users\Diego\Documents\GitHub\GamestonkTerminal\gamestonk_terminal.py

**Comment by Pranav4399** [comment]
I followed the imgur guide but I'm getting a ModuleNotFoundError: No module named 'flair'. Flair is already installed along with pytorch. How to resolve this ?

**Comment by DidierRLopes** [comment]
Hey guys,

I'm working during the weekend in order to fix the requirements.txt for everyone. Will let you know once that's done!

Thanks for your patience!

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
