### ISSUE TITLE
for those who encounter error when installing the python packages on Macos

### ISSUE THREAD

**Issue by sevensinjai** [DidierRLopes/GamestonkTerminal#42]
when you run `pip install -r requirement.txt` in your mac, if you encounter error related to `tensorflow`, `sentencepieces` or `matplotlib`, please check the followings:
1. your python and pip version required by tensorflow 2.x ( this project requires tensorflow 2.x , https://www.tensorflow.org/tutorials/quickstart/advanced )
2. some of my fds encounter error related to `ft2build`, they run `brew install freetype` then install the requirement again, it works ( like described here https://stackoverflow.com/questions/12363557/matplotlib-install-failure-on-mac-osx-10-8-mountain-lion/12790839 )

dun know if there is anyone facing the same errors, i hope it helps :)

**Comment by DidierRLopes** [comment]
Thank you for this :)

**Comment by formvoltron** [comment]
yes I'm having difficulty installing requirements.. error on sentencepiece

I'm not sure what you mean...  what about python, pip & tensorflow?


here is my error: 
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w5/b2scl24j5tv8n2_qgqg98wbc0000gr/T/pip-install-86tp_ou1/sentencepiece/setup.py'"'"'; __file__='"'"'/private/var/folders/w5/b2scl24j5tv8n2_qgqg98wbc0000gr/T/pip-install-86tp_ou1/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/w5/b2scl24j5tv8n2_qgqg98wbc0000gr/T/pip-pip-egg-info-ytc35j3y
         cwd: /private/var/folders/w5/b2scl24j5tv8n2_qgqg98wbc0000gr/T/pip-install-86tp_ou1/sentencepiece/
    Complete output (5 lines):
    Package sentencepiece was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sentencepiece.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'sentencepiece' found
    Failed to find sentencepiece pkgconfig

**Comment by formvoltron** [comment]
OK So I have python3.9.2  And TF says up to 3.8 for python.  Is this really causing the problem?

**Comment by shadycuz** [comment]
@formvoltron Most likely. We are curently working on increasing this project's support for python versions. As of now it only supports `3.6.8` that we know of.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
