### ISSUE TITLE
scipy==1.6.1

### ISSUE THREAD

**Issue by yonoflow** [DidierRLopes/GamestonkTerminal#43]
This came through when installing requirements.txt on Mac:

ERROR: Could not find a version that satisfies the requirement scipy==1.6.1
ERROR: No matching distribution found for scipy==1.6.1

**Comment by rwinte** [comment]
On a Mac you should be using pip3 to perform the installation. The default pip executable is Python 2 rather than Python 3.

**Comment by jftuga** [comment]
> On a Mac you should be using pip3 to perform the installation. The default pip executable is Python 2 rather than Python 3.

This is not working for me on Windows 10. I am using the recommended `python 3.6.8` as well as `pip 21.0.1`.

I get the exact same error message.

**Comment by rwinte** [comment]
I was able to finish the installation on MacOS 11.2.2 by using Python 3 from Anaconda rather than the system-installed version. This is Python 3.8.2.

I created a venv and installed using:
/path/to/anaconda/bin/python -m venv <venv directory>
source <venv directory>/bin/activate
pip install -r requirements.txt

**Comment by verchalent** [comment]
Ran into the same issue. scipy 1.6.1 is the latest on pypi.org, but the latest compatible with Python 3.6.8 (suggested / tested version) is 1.5.4

**Comment by shmup** [comment]
This isn't mac specific

On linux, and funnily enough I've worked backwards from 3.9.1 for a bit before seeing this was dev'd against 3.6.8, but alas, here I am hah

**Comment by yonoflow** [comment]
It worked for me by changing in requirements.txt just to scipy instead of scipy==1.6.1
What happens is apparently that  scipy is being installed regardless of the version.

**Comment by verchalent** [comment]
Confirming @shmup 's comment, it's not mac specific. I am hitting it on Linux using py 3.6.8 and also worked backwards from the latest py version. Changing from scipy==1.6.1 to scipy in requirements allowed me to get past this one. This change with Py 3.6.8 still yielded a bunch of minor errors and warnings in the modules installs, but was the first combo that allowed me to actually run the terminal.

**Comment by DidierRLopes** [comment]
Hey guys,

Sorry, this was my bad. The scipy version I'm actually using is 1.4.1. 

I'm fixing the requirements this weekend. Bear with me :)

**Comment by verchalent** [comment]
> Hey guys,
> 
> Sorry, this was my bad. The scipy version I'm actually using is 1.4.1.
> 
> I'm fixing the requirements this weekend. Bear with me :)

Heros are allowed to make mistakes.

**Comment by shadycuz** [comment]
We like the terminal!

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
