### ISSUE TITLE
TimeSeriesCrossValidation cannot be installed on Mac

### ISSUE THREAD

**Issue by yonoflow** [DidierRLopes/GamestonkTerminal#44]
When installing requirements.txt below Warning is mentioned but the protocol continues until shows an Error when trying to use the TimeSeriesCrossValidation.
Does anyone else have that issue?

Cloning https://github.com/DidierRLopes/TimeSeriesCrossValidation (to revision 1e29d393204abb3bde23ff3f15258ed85d3b263e) to /private/var/folders/l2/4cfnd_1x137ckrhhhxts8dym0000gn/T/pip-install-84wtkg3g/timeseriescrossvalidation_a0a31939a46b4e00840c584a15a790ad
  Running command git clone -q https://github.com/DidierRLopes/TimeSeriesCrossValidation /private/var/folders/l2/4cfnd_1x137ckrhhhxts8dym0000gn/T/pip-install-84wtkg3g/timeseriescrossvalidation_a0a31939a46b4e00840c584a15a790ad
  **xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun**
**WARNING: Discarding git+https://github.com/DidierRLopes/TimeSeriesCrossValidation@1e29d393204abb3bde23ff3f15258ed85d3b263e. Command errored out with exit status 1: git clone -q https://github.com/DidierRLopes/TimeSeriesCrossValidation /private/var/folders/l2/4cfnd_1x137ckrhhhxts8dym0000gn/T/pip-install-84wtkg3g/timeseriescrossvalidation_a0a31939a46b4e00840c584a15a790ad Check the logs for full command output.**

**Comment by yonoflow** [comment]
seems like Xcode download is necessary 

that could help:

https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/

**Comment by DidierRLopes** [comment]
Hey @yonoflow ,

I've not seen this issue before. Were you able to solve it with Xcode?

Thanks!

**Comment by yonoflow** [comment]
Hi @DidierRLopes 

it worked for me after installing Xcode. My Mac runs on BigSur 11.2.2

**Comment by clay-coffman** [comment]
Seems like you had a different issue but I ran into [this](https://stackoverflow.com/questions/51201515/pipenv-requires-an-egg-fragment-for-version-controlled-dependencies-warning-w) error trying to install this package using pipenv. It's a pretty simple fix, though (just run `pipenv install git+https://github.com/DidierRLopes/TimeSeriesCrossValidation#egg=TimeSeriesCrossValidation`).

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
