### ISSUE TITLE
So many dependencies!

### ISSUE THREAD

**Issue by exislow** [DidierRLopes/GamestonkTerminal#50]
It takes a very long time to install all dependencies. Are really all of the dependencies required? Maybe some are only for dev and could be moved e.g. to `requirements-dev.txt`? 

Also some of the dependencies have no version pinning. This is not a good practice.

What do you think? Less dependencies could increase deploy time...

**Comment by DidierRLopes** [comment]
Hey @exislow ,

You're absolutely right. And this is what I'm working on today!

I'll leave requirements.txt to what is absolutely necessary. Add poetry for package management, and make it possible to build a docker image from it.

This should make the installation much more simple, and also decrease deploy time since I think the current requirements.txt has libraries that aren't being used.

**Comment by exislow** [comment]
I am not a fan of peotry. Poetry can be really become really blown up. Also not all IDEs support poetry right now. E.g. IntelliJ cannot install files to my venv Python interpreter for a specific project. I would suggest to user requirements.txt as it is but with proper version pinning.

**Comment by BigCandyBunny** [comment]
Quite challenging to get the large list of libraries to function. Using pip on the requirements.txt file did not cut it for me. I use Miniconda and applied the command 'conda install -c conda-forge <library name>' successfully where my first attempt with pip failed. Also, I downloaded TensorFlow and PyTorch libraries directly  from its home page. If you have installed a library with pip which is not functioning, then you need to delete it with pip before re-installing it with other means.

I was able to install GamestonkTerminal with Python 3.7.9 and TensorFlow 2.4.1 and my complete list of dependencies can be found in the attached .yml file (dubbed as .txt since Github does recognize that format...).

I do think there is much to gain from streamlining the use of libraries and simplify installation for the end user of this impressive effort by Didier R. Lopes.

[gs_environment_latest.txt](https://github.com/DidierRLopes/GamestonkTerminal/files/6054985/gs_environment_latest.txt)

**Comment by piiq** [comment]
Hey @DidierRLopes 👋
This is the minimal list of requirements that allowed me to run the app on mac (python 3.8)

```
alpha-vantage
beautifulsoup4
fbprophet
finviz
flair
fundamentalanalysis
holidays
ipython
ipykernel
iso8601
matplotlib
numpy
pandas
pandas-ta
pmdarima
praw
prettytable
psaw
python_dateutil
pytrends
pytz
quandl
rapidfuzz
requests
scikit_learn
statsmodels
tensorflow
TimeSeriesCrossValidation @ git+https://github.com/DidierRLopes/TimeSeriesCrossValidation@1e29d393204abb3bde23ff3f15258ed85d3b263e
yfinance
```
Also to get the charts I had to specify a backend for matplotlib in `~/.matplotlib/marplotlibrc`. This was `backend: MacOSX` for me.

Do you want a PR with requirements change?

**Comment by exislow** [comment]
@piiq what versions did you use of the libraries and how did you have installed fbprophet on macOS? I am still stuck get it installed on Catalina.

**Comment by DidierRLopes** [comment]
Thank you @piiq for this list. Amazing work! No need for PR I'm currently installing libraries 1 by 1 with poetry in a docker image to make sure that the project builds smoothly with all necessary libraries. But your list is excellent, because it will allow me to compare my requirements.txt at the end with what you have, and I may ping you if there are any differences.

@exislow my idea was to export the poetry requirements to a requirements.txt file and have:
- Docker image to run this resulting requirement list. This will be useful for non devs as they'll be able to get the app deployed smoothly.
- Keep the poetry files for later use, and/or for people who like it, and prefer to use poetry within a pyenv.
I'm new to both poetry and dockers, but I thought that this was the way that would make the most people happy. Let me know if you think otherwise.

**Comment by piiq** [comment]
@exislow i use latest versions available on pip. 
I use pip 20 and fbprophet installs fine. It has some the school setup.py installation that's deprecated and removed in pip 21. 
I'm on Big Sur

**Comment by exislow** [comment]
@piiq I will try to downgrade pip. Thanks.

@DidierRLopes I have send you a pull request with basic refactoring.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
