### ISSUE TITLE
Would love to install this and work it out but this is the first time im using python. 

### ISSUE THREAD

**Issue by enriquevoss** [DidierRLopes/GamestonkTerminal#65]
Can you help an absolute beginner how to start and use this?

Okay so basically im an absolute beginner and coding but ive been investing for a while and wanted to give this a shot but i dont get it. :D Please help?  Could you make a more detailed installation description in steps?

Thanks!

**Comment by DidierRLopes** [comment]
Hey @enriquevoss ,

Yes, we've been working to improve the installation process during the weekend.

Will have something soon, along with a "Getting Started" document. I'll let you know once that happens in here.
Didier

**Comment by BrettAlan128** [comment]
I would like to know the installation details as well. I am doing the same things people are saying to do. At least I think anyways, and I am error message while trying to run the  `pip install -r requirements.txt`

**Comment by shadycuz** [comment]
@enriquevoss @breck7 

We will have an update out this week which will increase compatibility and add docker container support. We will let you know when its out.

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
