### ISSUE TITLE
How to get it up and running on macOS Big Sur

### ISSUE THREAD

**Issue by simprecicchiani** [DidierRLopes/GamestonkTerminal#70]
Hi, I saw the maintainer is planning to release a documentation. In the meanwhile I wanted to share my experience installing and running the code on macOS.
I had python3 previously setup with Anaconda (installed with homebrew `brew install --cask anaconda`).
Cloned the repo with `git clone https://github.com/DidierRLopes/GamestonkTerminal.git`.
`cd` into the repo directory and then `pip3 install -r requirements.txt`.
Then I tried to run the script but some errors came out.
First prawcore said it was outdated. 
Second `Importing plotly failed. Interactive plots will not work.` solved with `pip install --upgrade plotly`.
Finally the code was running fine but crashed every time a graph had to show up. I ended up changing and updating some dependencies in `./requirements.txt`:
```diff
- praw==7.1.4
- prawcore==1.5.0
+ praw==7.2.0
+ prawcore==2.0.0
...
- matplotlib==3.1.1
+ matplotlib==3.3.3
```
 then again `pip3 install -r requirements.txt`.

Hope this help someone while waiting for an official starting guide. Congrats for this amazing project!

**Comment by universvm** [comment]
In my case I also needed the scipy version of `1.4.1.` as mentioned in #43 and potentially if you haven't installed XCode CLI utilities you might have to run `xcode-select --install` and `brew install gcc `.

**Comment by DidierRLopes** [comment]
Thank you for feedback guys! @simprecicchiani and @universvm 

I'm still doing some tests around Windows installation with poetry and pip install. I've checked with OS and it seems that the requirements should be good to go. I'll update this soon. 

Thanks for feedback :)

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
